name: SkyCite
version: '1.0-SNAPSHOT'
main: fr.tetemh.skycite.SkyCite
api-version: '1.21'
authors: [ tetemh ]
libraries:
    - com.zaxxer:HikariCP:4.0.3
    - org.mariadb.jdbc:mariadb-java-client:3.0.8
depend: [FancyNpcs]
commands:
    init:
        description: Initialise le plugin de cité
        permission: skycite.init
        aliases: i
        permission-message: Non Non Non tu essaies de faire quoi là !
    money:
        description: Voir votre money
        permission: skycite.money
        permission-message: Non Non Non tu essaies de faire quoi là !
    debug:
        description: DEBUG
        permission: skycite.debug
        permission-message: Non Non Non tu essaies de faire quoi là !
    reloadnpc:
        description: Reload Citizen NPC
        permission: skycite.reloadnpc
        permission-message: Non Non Non tu essaies de faire quoi là !
    event:
        description: Gestion des events
        permission: skycite.event
        permission-message: Non Non Non tu essaies de faire quoi là !

